### ISSUE TITLE
audio clips and pops when thruster audio plays in rapid succession 

### ISSUE THREAD

**Issue by vanfleet-dev** [vanfleet-dev/Open_Source_2D_Rougelike_Space_Shooter#1]
#### Godot version:
v3.4.4 stable

#### OS/device including version:
ubuntu 20.04.4 lts

#### Issue description:
When trying to modify the audio for the player ship thrusters I have found the bug(s) detailed below:

https://github.com/godotengine/godot/issues/22016
https://github.com/godotengine/godot/issues/12307

It seems there are multiple sources for the audio clipping and pops introduced by changing the audio file. Some are from the audio file being started and stopped in rapid succession.

The way [ThrustersAudioPlayer](https://github.com/vanfleet-dev/Open_Source_2D_Rougelike_Space_Shooter/blob/main/project/Ships/Player/ThrustersAudioPlayer.tscn)   (AudioStreamPlayer2D) and [LoopingAudioStreamPlayer2D.gd](https://github.com/vanfleet-dev/Open_Source_2D_Rougelike_Space_Shooter/blob/main/project/Common/LoopingAudioStreamPlayer2D.gd) are setup to use three different audio files to fade into and out of the loop is a possible source of issue. When new audio plays while previous audio is finishing you get a clip.

[ThrustersAudioPlayer](https://github.com/vanfleet-dev/Open_Source_2D_Rougelike_Space_Shooter/blob/main/project/Ships/Player/ThrustersAudioPlayer.tscn) is added to the scene in  [PlayerShip.tscn](https://github.com/vanfleet-dev/Open_Source_2D_Rougelike_Space_Shooter/blob/main/project/Ships/Player/PlayerShip.tscn) line 55. The node is instantiated in [Travel.gd](https://github.com/vanfleet-dev/Open_Source_2D_Rougelike_Space_Shooter/blob/main/project/Ships/Player/States/Travel.gd) script lines 7 and 15-19.

**Comment by Kim-Lancaster** [comment]
Hey, I took a look at this and I think the simplest thing to do would be to remove the fade in fade out loops and see if we still get the same popping and clipping.  I'll check it out and let you know!

**Comment by vanfleet-dev** [comment]
Thank you. I added a new thruster audio loop for testing with your changes.

**Comment by Kim-Lancaster** [comment]
I changed the code to only use one audio file for the thrusters. But, the audio sounds abrupt now without the fade-in fade-out, because it's initiating from the movement of the player's ship.  I tried initiating it from the user key press and it makes for a better sound transition.  If your interested in that I can pull request with that included.

**Comment by vanfleet-dev** [comment]
That's great! I'm fine with the additional change.

**Comment by vanfleet-dev** [comment]
Fixed by Kimberly Lancaster on commit [a19c53d](https://github.com/vanfleet-dev/Open_Source_2D_Rougelike_Space_Shooter/commit/a19c53d17c824f9fc3cf9b54db89445c44e4c324).
